CREATE TABLE IF NOT EXISTS books (
  id     VARCHAR(36)  NOT NULL,
  title  VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  isbn   VARCHAR(20)  DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
